### ISSUE TITLE
Open GVFS (smb, webdev) directories doesn't work on 7.5.0

### ISSUE THREAD

**Issue by xlejo** [flathub/org.onlyoffice.desktopeditors#105]
Opening a GVFS directory (via SMB in my case) stops to work on 7.5.0. If you open the file through Nautilus, you will be able to see it, but when you save it will not be saved.

Rollback to 7.4.1 solves the problem.

Steps to rollback:

List commits of `app/org.onlyoffice.desktopeditors/x86_64/stable`.

```
$ flatpak remote-info --log flathub app/org.onlyoffice.desktopeditors/x86_64/stable                                                                                             
        ID: org.onlyoffice.desktopeditors
       Ref: app/org.onlyoffice.desktopeditors/x86_64/stable
      Arch: x86_64
    Branch: stable
Collection: org.flathub.Stable
  Download: 341.8 MB
 Installed: 997.5 MB
   Runtime: org.freedesktop.Platform/x86_64/22.08
       Sdk: org.freedesktop.Sdk/x86_64/22.08

    Commit: 70a78be0342922793f595d589827c9cae741989d66142f8d7424bb748a50076c
    Parent: 5f9bd38d147b8762badb6596d8a91117f8886459c6a6e2e168f93194da807b7e
   Subject: Update version to 7.5.0 (#104) (729303d3)
      Date: 2023-10-30 09:59:06 +0000
   History: 

    Commit: 5f9bd38d147b8762badb6596d8a91117f8886459c6a6e2e168f93194da807b7e
   Subject: Update to version 7.4.1 (#102) (8991c8fd)
      Date: 2023-08-04 15:22:58 +0000

    Commit: 979967e87538aa2101a84957fb9c908959db94f7423946884b2a51d68e2a364f
   Subject: Update version to 7.4.0 (#99) (9ca065dc)
      Date: 2023-06-27 07:27:43 +0000
<truncated>
```

Update app via commit and mask to prevent updates (optional). 

```
$ flatpak update --commit=5f9bd38d147b8762badb6596d8a91117f8886459c6a6e2e168f93194da807b7e app/org.onlyoffice.desktopeditors/x86_64/stable
$ flatpak mask app/org.onlyoffice.desktopeditors/x86_64/stable
```

**Comment by zalaare** [comment]
I'm running into this issue as well with the latest version.  I'll try to rollback and and test.

```
flatpak remote-info --user --log flathub app/org.onlyoffice.desktopeditors/x86_64/stable

ONLYOFFICE Desktop Editors - Office productivity suite

        ID: org.onlyoffice.desktopeditors
       Ref: app/org.onlyoffice.desktopeditors/x86_64/stable
      Arch: x86_64
    Branch: stable
   Version: 8.1.1
   License: AGPL-3.0-only
Collection: org.flathub.Stable
  Download: 296.2 MB
 Installed: 866.8 MB
   Runtime: org.freedesktop.Platform/x86_64/23.08
       Sdk: org.freedesktop.Sdk/x86_64/23.08

    Commit: 00cf2c5eb20170eac9336431cab9f57abe71cd83e079f69ea77bf0650a12f75f
    Parent: cabc6c77f64689a4239d51ba66974d58cb7b536607aca371e247c6a7ad56df20
   Subject: Update version to 8.1.1 (#121) (7bd514b1)
      Date: 2024-07-19 07:23:57 +0000
   History: 

    Commit: cabc6c77f64689a4239d51ba66974d58cb7b536607aca371e247c6a7ad56df20
   Subject: Update version to 8.1.0 (4b18b90c)
      Date: 2024-06-25 09:59:20 +0000

    Commit: c9f73db43c9639df65e597108eb4c685025fe484fde05f73f650d05f9ea28512
   Subject: Update version to 8.0.1 (#117) (a88ad400)
      Date: 2024-03-04 15:34:56 +0000

    Commit: a38db7bbfaa18eda6d26e9d113ce850c077bf533d9ebf5aa7e34988a58b91b28
   Subject: Update version to 8.0.1 (#117) (a88ad400)
      Date: 2024-03-04 15:34:56 +0000

    Commit: a5d669920d9b1d3c685bba8d195c078556cbfb223b572354e7d190d7004a1487
   Subject: Update version to 8.0.0 (#116) (76d3ec86)
      Date: 2024-02-07 12:48:06 +0000

    Commit: 3c47514eb66f671d9df5e6fab8b5463f275f56cd1df827461f120735c56db12a
   Subject: Update version to 7.5.1 (#107) (dc948b65)
      Date: 2023-11-20 08:28:21 +0000

    Commit: 70a78be0342922793f595d589827c9cae741989d66142f8d7424bb748a50076c
   Subject: Update version to 7.5.0 (#104) (729303d3)
      Date: 2023-10-30 09:59:06 +0000
```
